// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZOCyIyA-rso74x7qWSuJltGiqMZMrqdo',
    appId: '1:450727470597:web:a1a1646d2ce21fc5285e6c',
    messagingSenderId: '450727470597',
    projectId: 'ecommerceapp-e301c',
    authDomain: 'ecommerceapp-e301c.firebaseapp.com',
    storageBucket: 'ecommerceapp-e301c.appspot.com',
    measurementId: 'G-EX87D7KKZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsuoLR_gZ28tDLsOSsX6iCq0EPTaejy9c',
    appId: '1:450727470597:android:4de666faa99ef282285e6c',
    messagingSenderId: '450727470597',
    projectId: 'ecommerceapp-e301c',
    storageBucket: 'ecommerceapp-e301c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABzLGBPhNTE5lsaTU3LuC9jMuTJxKn86g',
    appId: '1:450727470597:ios:5144e14c5837b4cc285e6c',
    messagingSenderId: '450727470597',
    projectId: 'ecommerceapp-e301c',
    storageBucket: 'ecommerceapp-e301c.appspot.com',
    iosBundleId: 'com.example.tStore',
  );
}
